### ISSUE TITLE
资源失效

### ISSUE THREAD

**Issue by touyouzei** [PhilosopherZ/Meteorological-Books#3]
前辈你好!
https://github.com/PhilosopherZ/Meteorological-Books/blob/master/Atmospheric-boundary-layer/Fundamentals-of-Fluid-Mechanics-7th-Edition-By-Munson.pdf
这个链接打不开了，不知是不是资源失效了呢？可否进行补链呢？感谢~

**Comment by zxdawn** [comment]
@touyouzei 直接去这个[目录](https://github.com/PhilosopherZ/Meteorological-Books/tree/master/Atmospheric-boundary-layer)下载就行。

**Comment by touyouzei** [comment]
收到！谢谢前辈回复，刚接触github，从气象家园看到您贴的链接，谢谢指导喽！


 
---原始邮件---
发件人: "Xin Zhang"<notifications@github.com>
发送时间: 2019年7月21日(星期日) 中午11:01
收件人: "PhilosopherZ/Meteorological-Books"<Meteorological-Books@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"touyouzei"<676868198@qq.com>;
主题: Re: [PhilosopherZ/Meteorological-Books] 资源失效 (#3)



@touyouzei 直接去这个目录下载就行。

**Comment by PhilosopherZ** [comment]
> 前辈你好!
> https://github.com/PhilosopherZ/Meteorological-Books/blob/master/Atmospheric-boundary-layer/Fundamentals-of-Fluid-Mechanics-7th-Edition-By-Munson.pdf
> 这个链接打不开了，不知是不是资源失效了呢？可否进行补链呢？感谢~

谢谢指出，已修改。
